export const carteTarocchi = [
  {
    Titolo: "Il Matto",
    Numerologia: "0",
    Elementi: ["Aria"],
    Lettura: "",
    Chakra: "Corona",
    PianetaOroscopo: "Urano",
    Significato: "libertà, fede, inesperienza, innocenza",
    SignificatoInverso: "Essere creduloni e ingenui, Correre rischi inutili, Non essere seri quando necessario, Essere sciocchi o distratti, Mancare di esperienza, Non rispettare tradizioni e limiti consolidati, Comportarsi in modo inappropriato",
    BreveDescrizione: "Liberarsi dai limiti, Esprimere gioia e vigore giovanile, Essere di mentalità aperta"
  },
  {
    Titolo: "Il Mago",
    Numerologia: "1",
    Elementi: ["Mercurio"],
    Lettura: "",
    Chakra: "Gola",
    PianetaOroscopo: "Mercurio",
    Significato: "capacità, empowerment, attività",
    SignificatoInverso: "Gonfiare se stessi Ego, Abusare dei talenti, Manipolare o ingannare gli altri, Essere troppo aggressivi, Usare illusioni a buon mercato per abbagliare gli altri, Rifiutarsi di investire il tempo e gli sforzi necessari per padroneggiare la propria arte, Prendere scorciatoie",
    BreveDescrizione: "Intraprendere azioni appropriate, Ricevere guida da un potere superiore, Diventare un canale della volontà divina"
  },
  {
    Titolo: "La Papessa",
    Numerologia: "2",
    Elementi: ["Acqua", "Luna"],
    Lettura: "",
    Chakra: "Terzo Occhio",
    PianetaOroscopo: "Luna",
    Significato: "intuizione, riflessione, purezza, iniziazione",
    SignificatoInverso: "Essere distaccati, Ossessionati da segreti e cospirazioni, Rifiutare la guida dello spirito o dell'intuizione, Rivelare tutto, Ignorare le sensazioni viscerali, Rifiutarsi di farsi coinvolgere, anche quando il coinvolgimento è appropriato",
    BreveDescrizione: "Ascoltare i propri sentimenti e intuizioni, Esplorare una spiritualità non convenzionale, Mantenere segreti"
  }, 
  { 
    Titolo: "L'Imperatrice", 
    Numerologia: "3", 
    Elementi: ["Terra","Venere"], 
    Lettura: "", 
    Chakra: "Cuore", 
    PianetaOroscopo: "Venere", 
    Significato: "fertilità, produttività, maturità, nutrimento", 
    SignificatoInverso: "Eccessivamente indulgente, Essere avido, Soffocare qualcuno con attenzioni, Debilitare qualcuno essendo iperprotettivo, Inibire la produttività ossessionandosi sulla produttività, Essere sopraffatto da comportamenti di dipendenza", 
    BreveDescrizione: "Curare sé stessi e gli altri, Portare frutto, Celebrare il proprio corpo" 
  }, 
  { 
    Titolo: "L'Imperatore", 
    Numerologia: "4", 
    Elementi: ["Fuoco","Ariete"], 
    Lettura: "", 
    Chakra: "Plesso Solare", 
    PianetaOroscopo: "Marte", 
    Significato: "autorità, regolamentazione, direzione, struttura", 
    SignificatoInverso: "Micromanaging, Schiacciare la creatività degli altri con un approccio rigido, Approccio ferreo, Insistere nel fare a modo proprio, Assumere una mentalità dittatoriale, Usare la forza palese per raggiungere i propri obiettivi e mantenere l'ordine",
    BreveDescrizione: "Esercitare l'autorità, Definire i limiti, Dirigere il flusso del lavoro"
  },
  {
    Titolo: "Il Papa",
    Numerologia: "5",
    Elementi: ["Terra","Toro"],
    Lettura: "",
    Chakra: "Gola",
    PianetaOroscopo: "Giove",
    Significato: "guida, conoscenza, rivelazione, fede",
    SignificatoInverso: "Usare l'esperienza come mezzo per manipolare o fuorviare gli altri, Essere dogmatici, Favorire la tradizione rispetto a ciò che è opportuno o necessario, Eseguire rituali vuoti, Nascondere la saggezza, Limitare l'accesso alle verità spirituali o agli dei",
    BreveDescrizione: "Insegnare o guidare gli altri, Cercare la verità, Chiedere guida a un potere superiore"
  },
  {
    Titolo: "Gli Amanti",
    Numerologia: "6",
    Elementi: ["Aria","Gemelli"],
    Lettura: "",
    Chakra: "Cuore",
    PianetaOroscopo: "Venere",
    Significato: "amore, passione, unità, scelta",
    SignificatoInverso: "Passione debilitante, Permettere a un malsano desiderio d'amore di motivare comportamenti distruttivi, Interrompere l'unità, Agire contro i migliori interessi di coloro che si prendono cura di te, Decisioni mal informate",
    BreveDescrizione: "Essere innamorati, Mostrare il proprio amore agli altri, Esprimere passione o sentimenti romantici"
  },
  {
    Titolo: "Il Carro",
    Numerologia: "7",
    Elementi: ["Acqua","Cancro"],
    Lettura: "",
    Chakra: "Plesso Solare",
    PianetaOroscopo: "Luna",
    Significato: "avanzamento, vittoria, trionfo, successo",
    SignificatoInverso: "Riposare sugli allori, Calpestare i sentimenti o le aspettative degli altri, Concentrarsi più sui successi passati che sulle opportunità future, Non riuscire a frenare il comportamento impulsivo",
    BreveDescrizione: "Superare le barriere, Avanzare con sicurezza e autorità, Raggiungere l'apice del successo"
  },
  {
    Titolo: "La Forza",
    Numerologia: "8",
    Elementi: ["Fuoco","Leone"],
    Lettura: "",
    Chakra: "Cuore",
    PianetaOroscopo: "Sole",
    Significato: "disciplina, audacia, autodisciplina, potere, vitalità",
    SignificatoInverso: "Accostarsi alla debolezza, anche quando sai che danneggerà la tua salute e la tua felicità, Languire nella dipendenza, Lasciare che i tuoi istinti ti domino e ti conquistino, Non riuscire a prendere posizione",
    BreveDescrizione: "Imporre restrizioni a se stessi per il proprio beneficio, Sottomettere le proprie passioni alla ragione, Resistere agli impulsi che vanno contro i propri interessi"
  },
  {
    Titolo: "L'Eremita",
    Numerologia: "9",
    Elementi: ["Terra","Vergine"],
    Lettura: "",
    Chakra: "Terzo Occhio",
    PianetaOroscopo: "Mercurio",
    Significato: "solitudine, esperienza, immobilità, ritiro",
    SignificatoInverso: "Essere un solitario, Temere il contatto con gli altri, Diventare un saputello, Affermare di essere competente, Nascondere le proprie capacità e i propri talenti per paura di essere indegni",
    BreveDescrizione: "Diventare o cercare un guru, Andare in ritiro, Ricaricare le batterie spirituali o creative"
  },
  {
    Titolo: "La Ruota della Fortuna",
    Numerologia: "10",
    Elementi: ["Fuoco","Giove"],
    Lettura: "",
    Chakra: "Corona",
    PianetaOroscopo: "Giove",
    Significato: "fortuna, casualità, cicli, karma, destino, rivoluzione",
    SignificatoInverso: "Perdere soldi al gioco d'azzardo, Rifiutarsi di fare la propria parte per portare a termine un piano, Adottare un approccio fatalistico alla vita, Combattere il corso naturale degli eventi",
    BreveDescrizione: "Lasciare che gli eventi si svolgano, Vedere il modello più ampio negli eventi quotidiani, Fidarsi della fortuna"
  },
  {
    Titolo: "La Giustizia",
    Numerologia: "11",
    Elementi: ["Aria","Bilancia"],
    Lettura: "",
    Chakra: "Cuore",
    PianetaOroscopo: "Venere",
    Significato: "equilibrio, legge, correttezza, obiettività",
    SignificatoInverso: "Emettere critiche aspre, Essere ossessionati da regole e regolamenti, Seguire le regole anche quando è distruttivo o controproducente farlo, Confondere decisioni affrettate con azioni tempestive, Fare favoritismi",
    BreveDescrizione: "Prendere una decisione obiettiva, Valutare attentamente una questione prima di agire, Adattare opportunamente la propria reazione a una situazione"
  },
  {
    Titolo: "L'Appeso",
    Numerologia: "12",
    Elementi: ["Acqua"],
    Lettura: "",
    Chakra: "Plesso Solare",
    PianetaOroscopo: "Nettuno",
    Significato: "illuminazione, sacrificio, prospettiva, sospensione, inversioni",
    SignificatoInverso: "Essere infedeli a se stessi e ai propri valori, Rifiutarsi di fare sacrifici quando è il caso, Rifiutarsi di adattarsi a nuove situazioni, Incolpare gli altri, Trarre profitto a spese degli altri",
    BreveDescrizione: "Vedere opportunità di crescita in eventi spiacevoli, Sperimentare un cambiamento radicale nella prospettiva personale, Trarre il meglio da un cambiamento imprevisto nella propria vita o nel lavoro"
  },
  {
    Titolo: "La Morte",
    Numerologia: "13",
    Elementi: ["Acqua","Scorpione"],
    Lettura: "",
    Chakra: "Plesso Solare",
    PianetaOroscopo: "Plutone",
    Significato: "fine, Conclusione, transizione, passaggio, partenza",
    SignificatoInverso: "Ossessionarsi sulla morte e sul morire, Rifiutarsi di abbandonare vecchie abitudini o relazioni malsane, Insistere sul fatto che tutto e tutti debbano rimanere uguali per sempre, Non prendersi cura di sé",
    BreveDescrizione: "Mettere fine a una fase spiacevole della vita, Riconoscere e celebrare la conclusione di qualcosa, Mettere da parte le cattive abitudini"
  },
  {
    Titolo: "La Temperanza",
    Numerologia: "14",
    Elementi: ["Fuoco","Sagittario"],
    Lettura: "",
    Chakra: "Cuore",
    PianetaOroscopo: "Giove",
    Significato: "fusione, sintesi, mediazione, combinazione, armonia",
    SignificatoInverso: "Andare agli estremi, Interrompere gli sforzi di gruppo, Ignorare approcci sani alla vita, Diventare dipendenti, Praticare la gola, Fare a pezzi qualcosa o qualcuno, Rompere le alleanze",
    BreveDescrizione: "Mettere insieme gli opposti, Moderare le proprie azioni o emozioni, Trovare un punto di mezzo terra"
  },
  {
    Titolo: "Il Diavolo",
    Numerologia: "15",
    Elementi: ["Terra","Capricorno"],
    Lettura: "",
    Chakra: "Radice",
    PianetaOroscopo: "Saturno",
    Significato: "ombra, materialismo, schiavitù, illusione",
    SignificatoInverso: "Dare eccessiva importanza alle apparenze, Voler sempre di più, Dare più valore ai beni che alle persone o alle relazioni, Permettere agli istinti bassi di governare la propria vita, Essere egoisti, Attribuire i propri impulsi oscuri a forze esterne o ad altre persone",
    BreveDescrizione: "Apprezzare i lussi che la vita ha da offrire, Sentirsi a proprio agio nella propria pelle, Godersi la propria sessualità"
  },
  {
    Titolo: "La Torre",
    Numerologia: "16",
    Elementi: ["Fuoco","Marte"],
  	Lettura: "",
    Chakra: "Plesso Solare",
    PianetaOroscopo: "Marte",
    Significato: "demolizione, sconvolgimento, decostruzione, disastro, distruzione",
    SignificatoInverso: "Aggrapparsi a tradizioni che reprimono la crescita, abbandonarsi a una cecità volontaria, rifiutare l'evidenza che il cambiamento è necessario, ignorare la guida di un potere superiore, adottare comportamenti distruttivi in ​​modo malizioso",
    BreveDescrizione: "Abbandonare vecchie abitudini e mentalità limitanti, spianare la strada a una nuova crescita, dissipare l'influenza di un ego gonfio"
  },
  {
    Titolo: "La Stella",
    Numerologia: "17",
    Elementi: ["Aria","Acquario"],
  	Lettura: "",
  	Chakra: "Terzo Occhio",
  	PianetaOroscopo: "Urano",
  	Significato: "speranza, ottimismo, apertura, certezza, fede, desiderio, verità",
  	SignificatoInverso: "Negare verità spiacevoli, Negare la responsabilità personale e dire: 'Le cose accadono e basta!', Ignorare segni e presagi, Preferire l'illusione alla realtà, Diffondere pessimismo e avarizia di spirito",
  	BreveDescrizione: "Sperare nel meglio, Credere che le cose belle accadano alle brave persone, Vedere gli eventi nella migliore luce possibile"
  },
  {
  	Titolo: "La Luna",
  	Numerologia: "18",
  	Elementi: ["Acqua","Pesci"],
  	Lettura: "",
  	Chakra: "Terzo Occhio",
  	PianetaOroscopo: "Nettuno",
  	Significato: "mistero, fantasia, immaginazione, sogni, incertezza",
  	SignificatoInverso: "Diventare incapaci di separare la fantasia dalla realtà, Soffrire di deliri, Perdere l'apprezzamento per il fantastico o il magico, Adottare una mentalità spietatamente logica, Non riuscire ad apprezzare i misteri della vita",
  	BreveDescrizione: "Godere di sane fantasie e sogni ad occhi aperti, Usare la propria immaginazione, Praticare la magia o celebrare la magia della vita quotidiana"
  },
  {
  	Titolo: "Il Sole",
  	Numerologia: "19",
  	Elementi: ["Fuoco","Sole"],
  	Lettura: "",
  	Chakra: "Plesso Solare",
  	PianetaOroscopo: "Sole",
  	Significato: "gioia, brillantezza, convalida, attenzione, energia",
  	SignificatoInverso: "Essere abbagliati dai propri successi, Essere assorbiti dalla propria immagine di sé, Sentirsi frettolosi e distratti, Sforzarsi fino allo sfinimento, Sopravvalutare le proprie capacità o travisare i propri successi",
  	BreveDescrizione: "Vedere le cose chiaramente, Provare una gioia intensa, Celebrare i propri successi"
  },
  {
  	Titolo: "Il Giudizio",
  	Numerologia: "20",
  	Elementi: ["Fuoco"],
  	Lettura: "",
  	Chakra: "Corona",
  	PianetaOroscopo: "Plutone",
  	Significato: "rinascita, rinnovamento, resurrezione, valutazione, invito",
  	SignificatoInverso: "Essere pesati sulla bilancia e trovati carenti, Non riuscire a essere all'altezza di uno standard ben definito, Essere colti a scherzare o a comportarsi male, Non riuscire a prepararsi per un esame che si sa che sta per arrivare, Rifiutare un'opportunità per reinventarsi",
  	BreveDescrizione: "Ricevere una chiamata al risveglio, Scoprire un nuovo scopo nella vita, Diventare totalmente e completamente se stessi"
  },
  {
  	Titolo: "Il Mondo",
  	Numerologia: "21",
  	Elementi: ["Terra","Saturno"],
  	Lettura: "",
  	Chakra: "Radice",
  	PianetaOroscopo: "Saturno",
  	Significato: "interezza, integrazione, totalità, completezza, pienezza",
  	SignificatoInverso: "Lasciare che avidità e invidia ti impediscano di godere di ciò che possiedi, Non riuscire a vedere il disegno più ampio negli eventi ordinari, Credere che tutto ciò che esiste possa essere toccato, contato o misurato, Non riuscire a vedere il divino riflesso in chi ti circonda",
  	BreveDescrizione: "Avere tutto, Conoscere e amare te stesso il più completamente possibile, Vedere l'interconnessione di tutte le cose e le persone"
  },
  {
  	Titolo: "Asso di Coppe",
  	Numerologia: "1",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "intuizione, spiritualità, affetto, motivazione",
  	SignificatoInverso: "Nascondere i propri sentimenti, Rifiutare l'opportunità di amare o essere amati, Intorpidirsi ai desideri spirituali, Rifiutare i consigli del proprio cuore, Diventare un burattino delle proprie emozioni, Indulgere nell'isteria o nell'ossessione",
  	BreveDescrizione: "Fidarsi dei propri sentimenti, Aprirsi allo spirito, Accettare e ricambiare l'affetto"
  },
  {
  	Titolo: "Due di Coppe",
  	Numerologia: "2",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "unione, attrazione, combinazione, affetto",
  	SignificatoInverso: "Bruciare i ponti, Rimanere intrappolati in una codipendenza malsana, Escludere chiunque tranne i propri eletti, Ossessionarsi per qualcuno che non ricambia il proprio affetto, Disperarsi di trovare l'anima gemella, Ingannarsi sul proprio vero orientamento",
  	BreveDescrizione: "Essere attratti da qualcuno, Desiderare qualcuno o qualcosa, Agire in base ai propri desideri"
  },
  {
  	Titolo: "Tre di Coppe",
  	Numerologia: "3",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "celebrazione, espressione, comunità, cordialità",
  	SignificatoInverso: "Scambiare la vertigine per vero affetto, Essere dominati da emozioni maniacali, Aspettarsi che tutti siano sempre Provi le stesse cose che provi tu, Pretendiamo un supporto irragionevole da amici o familiari, Festeggi in modo pericoloso o malsano",
  	BreveDescrizione: "Celebrare i tuoi sentimenti o i tuoi legami con gli altri, Esprimere gioia attraverso il canto, la danza o l'affetto fisico, Collaborare con altre persone che condividono i tuoi sentimenti"
  },
  {
  	Titolo: "Quattro di Coppe",
  	Numerologia: "4",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "noia, liInquietudine, letargia, stabilità, ingratitudine",
  	SignificatoInverso: "Essere annoiati, Sognare ad occhi aperti a scapito del proprio lavoro, Rifiutarsi di lasciarsi coinvolgere dalle opportunità, Dare per scontate persone e relazioni, Ignorare opportunità romantiche o spirituali, Rifiutare l'ispirazione, Sentire che tutto dovrebbe rimanere 'così com'è",
  	BreveDescrizione: "Mantenere la propria stabilità emotiva, Rifiutarsi di cedere a emozioni travolgenti, Apprezzare ciò che si ha e rifiutarsi di darlo per scontato"
  },
  {
  	Titolo: "Cinque di Coppe",
  	Numerologia: "5",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "perdita, disperazione, rivalutazione, rimpianto, incertezza, pentimento",
  	SignificatoInverso: "Rovinarsi in un dolore malsano o nell'autocommiserazione, Rifiutarsi di andare avanti e lasciar andare, Aggrapparsi al passato, Ossessionarsi su vite passate e amori passati, Non riuscire a vivere nel presente, Colpevolizzarsi per gli errori passati, Permettere alla paura di fallire di limitare i propri sforzi",
  	BreveDescrizione: "Riconoscere la perdita e andare avanti, Concentrarsi su come il bicchiere rimanga 'mezzo pieno', Trovare il lato positivo in una nuvola scura"
  },
  {
  	Titolo: "Sei di Coppe",
  	Numerologia: "6",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "carità, condivisione, sacrificio, cooperazione, equità",
  	SignificatoInverso: "Collegare il proprio senso di autostima alle valutazioni degli altri, Sforzarsi di apparire più bisognosi di quanto si sia in realtà, Accettare elemosine immeritate o non meritate, Vantarsi dei propri sforzi caritatevoli, Trarre profitto nei momenti di difficoltà, Rifiutarsi di condividere un peso",
  	BreveDescrizione: "Donare il proprio tempo e il proprio talento agli altri, Trarre soddisfazione dal sapere come i propri sforzi aiuteranno gli altri, Creare uno scenario 'win-win'"
  },
  {
  	Titolo: "Sette di Coppe",
  	Numerologia: "7",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "immaginazione, sogni, illusioni, obiettivi",
  	SignificatoInverso: "Ossessionarsi con paure immaginarie o conseguenze incerte, Cedere al terrorismo emotivo o politico, Trascorrere più tempo a sognare che a lavorare, Non riuscire a prevedere le possibili ripercussioni delle proprie scelte, Essere controllati dalla paura",
  	BreveDescrizione: "Motivarsi con immagini di successo futuro, Usare la visualizzazione per incoraggiare il progresso, Adottare un approccio fantasioso o creativo alla risoluzione dei problemi"
  },
  {
  	Titolo: "Otto di Coppe",
  	Numerologia: "8",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "desiderio, insoddisfazione, ricerca, partenza, ritiro",
  	SignificatoInverso: "Essere implacabili, Trovare difetti, Essere pignoli, Rifiutarsi di accontentarsi giù, scappare da problemi o confronti, dire: 'O la faccio a modo mio o l'autostrada!', insistere sugli errori e le delusioni del passato, minacciare di mollare come strategia per ottenere ciò che si vuole",
  	BreveDescrizione: "Volere qualcosa di meglio, tracciare la propria strada, rendersi conto che ci deve essere di più nella vita"
  },
  {
  	Titolo: "Nove di Coppe",
  	Numerologia: "9",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "soddisfazione, sensualità, lusso, piacere",
  	SignificatoInverso: "Essere compiaciuti, accontentarsi a spese degli altri, essere egoisti, indulgere eccessivamente, evitare il lavoro che deve essere fatto, rivendicare risultati o competenze che non si possiedono, non essere mai soddisfatti, non importa quanto si abbia",
  	BreveDescrizione: "Essere felici dei propri successi, riconoscere i propri talenti e capacità, gioire delle cose belle che la vita ha da offrire Offerta"
  },
  {
  	Titolo: "Dieci di Coppe",
  	Numerologia: "10",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "gioia, appagamento, emozione travolgente, vertigine",
  	SignificatoInverso: "Confrontare i propri successi o relazioni con standard di fantasia irrealistici, Vivere emozioni così intense da indebolire la capacità di affrontare la realtà, Sentirsi sopraffatti, Invidiare i successi e la felicità degli altri",
  	BreveDescrizione: "Avere più di quanto tu abbia mai sognato, Essere profondamente grati per tutto ciò che ti è stato dato, Riconoscere la mano di Dio nei doni che l'Universo ti porta"
  },
  {
  	Titolo: "Fante di Coppe",
  	Numerologia: "11",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "entusiasmo, prime impressioni, romanticismo, superficialità",
  	SignificatoInverso: "Scambiare una cotta per vero amore, Leggere intenzioni romantiche in azioni innocenti, Cercare freneticamente di impressionare gli altri, Indulgere in un sentimentalismo eccessivamente dolce, Fingere di avere più esperienze romantiche o spirituali di quelle che si possiedono",
  	BreveDescrizione: "Mostrare liberamente le proprie emozioni, Lanciarsi nel romanticismo, Nutrire una cotta segreta"
  },
  {
  	Titolo: "Cavaliere di Coppe",
  	Numerologia: "12",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "fervore, zelo, malumore, illuminazione",
  	SignificatoInverso: "Diventare un fanatico, Rifiutare le informazioni che suggeriscono che le tue intuizioni sono fuorvianti, Permettere alle tue emozioni di controllarti, Cedere alla gelosia, al confronto e alla pressione dei pari, Nascondere o ignorare le intuizioni intuitive",
  	BreveDescrizione: "Essere profondamente impegnato in una causa, Cedere a emozioni forti, dall'eccitazione alla depressione, Agire solo in base all'intuizione"
  },
  {
  	Titolo: "Regina di Coppe",
  	Numerologia: "13",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "intuizione, spiritualità, compassione, empatia, istinto",
  	SignificatoInverso: "Essendo così coinvolto in questioni spirituali, ti distacchi dal mondo, Permettere all'empatia di bloccarti (invece di ispirarti all'azione), Usare capacità psichiche per esercitare un'influenza nascosta, Crogiolarsi in emotività, sentimentalismo o autocommiserazione",
  	BreveDescrizione: "Lasciarsi commuovere dalla situazione altrui, Provare emozioni forti, Avere una compassione o un'empatia insolite"
  },
  {
  	Titolo: "Re di Coppe",
  	Numerologia: "14",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "saggezza, diplomazia, moderazione, compostezza",
  	SignificatoInverso: "Lasciarsi diventare rigidi e privi di emozioni, Prendere decisioni ingiuste basate su secondi fini, Prendere decisioni senza considerare il loro impatto emotivo sugli altri, Abusare dell'autorità spirituale, Usare la leva emotiva o spirituale per esercitare un controllo malsano sugli altri",
  	BreveDescrizione: "Mantenere il labbro superiore rigido, Essere coraggiosi e chiari di fronte a circostanze avverse, Condividere l'esperienza come un modo per confortare gli altri"
  },
  {
  	Titolo: "Asso di Spade",
  	Numerologia: "1",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "logica, oggettività, intelletto, scelta",
  	SignificatoInverso: "Applicare una logica spietata o distorta, Esultare per la propria intelligenza superiore, Usare il pensiero rapido per ingannare o confondere gli altri, Confondere giudizi affrettati con il pensiero rapido, Prendere decisioni senza pensare alle conseguenze",
  	BreveDescrizione: "Prendere decisioni oggettive, Applicare la logica, Ragionare per uscire da una situazione difficile"
  },
  {
  	Titolo: "Due di Spade",
  	Numerologia: "2",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "negazione, dibattito, impasse, tregua",
  	SignificatoInverso: "Rifiutare prove che sono in conflitto con convinzioni radicate, Discutere con gli altri solo per il gusto di farlo, Essere pignoli, Rimandare una decisione per paura di affrontare le conseguenze, Impedire agli altri di ottenere le informazioni di cui hanno bisogno per prendere Buone decisioni",
  	BreveDescrizione: "Rifiutarsi di prendere una decisione senza conoscere i fatti, Esplorare entrambi i lati di una discussione, Sostenere con passione ciò in cui si crede"
  },
  {
  	Titolo: "Tre di Spade",
  	Numerologia: "3",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "varianza, differenza, insoddisfazione, dolore, rifiuto",
  	SignificatoInverso: "Crogiolarsi nella disperazione, Lasciarsi completamente schiacciare dai pensieri, dalle parole o dalle azioni di un altro, Giudicarsi troppo duramente, Attenersi a uno standard di eccellenza irrealistico, Essere sinceri ma avere un peso sulle spalle",
  	BreveDescrizione: "Essere abbastanza coraggiosi da vedere le cose come sono realmente, Esercitare il proprio occhio critico, Essere il miglior critico di se stessi"
  },
  {
  	Titolo: "Quattro di Spade",
  	Numerologia: "4",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "meditazione, contemplazione, prospettiva, mentalità",
  	SignificatoInverso: "Non riuscire a riflettere sulle cose, scambiare la procrastinazione per riflessione, adottare un punto di vista e rifiutarsi di riconsiderare le proprie conclusioni, anche quando si presentano prove che confutano, permettere al caos e alla fantasia di dominare i propri pensieri",
  	BreveDescrizione: "Riflettere sui propri piani prima di metterli in atto, fermarsi a meditare o a schiarirsi la mente, prendersi del tempo per capire qualcuno o qualcosa prima di criticarlo"
  },
  {
  	Titolo: "Cinque di Spade",
  	Numerologia: "5",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "egoismo, ostilità, irrazionalità, autoconservazione",
  	SignificatoInverso: "approfittare degli altri, intimidire gli altri, agire in modo non etico, attaccare briga, usare parole per provocare gli altri nella violenza e nell'irrazionalità, ignorando le regole che hai accettato di rispettare, pensando a te stesso mentre permetti che gli altri subiscano danni, esultando per la vittoria",
    BreveDescrizione: "Agire nel tuo interesse, scegliere di difenderti, non tirarti indietro di fronte a disaccordi e discordie"
  },
  {
  	Titolo: "Sei di Spade",
  	Numerologia: "6",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "adattamento, aggiustamenti, scienza, viaggio",
  	SignificatoInverso: "Rifiutarsi di accettare che le cose siano cambiate, Fare la vittima, Rifiutare l'idea che le proprie azioni abbiano delle conseguenze, Applicare criteri scientifici a questioni di fede o confondere la fede con la scienza, Credere che il mondo intero dovrebbe essere come il tuo piccolo angolo",
  	BreveDescrizione: "Trarre il meglio da una brutta situazione, Riprendersi da una sconfitta, Ripristino delle aspettative"
  },
  {
  	Titolo: "Sette di Spade",
  	Numerologia: "7",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "disonestà, presunzione, furtività, supposizioni",
  	SignificatoInverso: "Rubare o mentire, Fare tutto ciò che si può fare francamente, semplicemente perché si può, Cercare un modo per aggirare le conseguenze, Giustificare un comportamento malvagio concentrandosi sulla malvagità degli altri, Non esaminare le proprie motivazioni e i propri pregiudizi",
  	BreveDescrizione: "Rifiutarsi di fare qualcosa di disonesto, anche quando non c'è alcuna possibilità di essere scoperti, Gestire una situazione difficile con finezza, Sottolineare le supposizioni"
  },
  {
  	Titolo: "Otto di Spade",
  	Numerologia: "8",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "restrizione, limitazione, confinamento, impotenza",
  	SignificatoInverso: "Sentirsi intrappolati, Essere persi in un labirinto di regole e regolamenti, Cedere alla disperazione, Fare la vittima, Permettere agli altri di dettare cosa si può e non si può fare, Essere resi impotenti, Avere pochissime opzioni, Non riuscire a cercare una via d'uscita",
  	BreveDescrizione: "Onorare i limiti, Rispettare le regole, Decidere di mettersi a dieta per il bene della propria salute"
  },
  {
  	Titolo: "Nove di Spade",
  	Numerologia: "9",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "rimorso, preoccupazione, sconvolto, conclusione",
  	SignificatoInverso: "Torturarsi con i rimpianti, Mettere in dubbio ogni mossa, Colpirsi per i propri errori, Depressione, Ossessionarsi per errori e dettagli trascurati, Rifiutarsi di gestire lo stress in modo sano, Rovinare la propria capacità di apprezzare il presente soffermandosi sul passato, Discutere decisioni irreversibili",
  	BreveDescrizione: "Rifiutarsi di preoccuparsi di ciò che non si può controllare, Rifiutare l'ansia, Giudicare le proprie prestazioni con gentilezza e dolcezza"
  },
  {
  	Titolo: "Dieci di Spade",
  	Numerologia: "10",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "esaurimento, rovina, disastro, resistenza, ossessione",
  	SignificatoInverso: "Accettare la sconfitta prematuramente, Guidare fino all'esaurimento totale, soprattutto mentale, avere un crollo mentale, essere ossessionati da un problema fino al punto di rottura, arrendersi, rifiutarsi di passare dal pensiero all'azione, pensieri profondamente malsani",
  	BreveDescrizione: "Vedere i segnali che hai raggiunto i tuoi limiti, prestare attenzione a ciò che il tuo corpo sta cercando di dirti, cedere al bisogno di riposo e rinnovamento"
  },
  {
  	Titolo: "Fante di Spade",
  	Numerologia: "11",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "studente, apprendista, borsa di studio, informazione",
  	SignificatoInverso: "Fingere di avere conoscenze o competenze che non si possiedono, imbrogliare a un esame, fingere interesse per ottenere favori, considerare solo le prove che supportano le conclusioni già tratte, rifiutare i saggi consigli di insegnanti esperti",
  	BreveDescrizione: "Seguire un corso di studi, porre buone domande, investire tempo nello studio e pratica"
  },
  {
  	Titolo: "Cavaliere di Spade",
  	Numerologia: "12",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "schiettezza, intelligenza, incisività, investigazione",
  	SignificatoInverso: "Affermare le proprie opinioni come fatti, Attaccare litigi, Iniziare discussioni, Usare insulti intelligenti per minare la fiducia degli altri, Gettare la ragione dalla finestra, Parlare senza tenere conto dei sentimenti degli altri, Andare a caccia di streghe, Distorcere le prove",
  	BreveDescrizione: "Dire ciò che si pensa, Far conoscere le proprie opinioni, Offrire critiche costruttive"
  },
  {
  	Titolo: "Regina di Spade",
  	Numerologia: "13",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "grazia, abilità, arguzia, fascino, attitudine",
  	SignificatoInverso: "Sapere esattamente cosa dire per distruggere Un'altra persona, Omettere informazioni critiche, Usare una lingua tagliente per irritare gli altri, Usare il sarcasmo, Imitare gli altri in modo scortese, Prendere alla leggera i meno fortunati, Essere irrispettosi, Non usare il talento che ti è stato dato",
  	BreveDescrizione: "Esercitare tatto o usare diplomazia, Disinnescare una situazione tesa, Sapere cosa dire e come dirlo"
  },
  {
  	Titolo: "Re di Spade",
  	Numerologia: "14",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "genio, competenza, decisione, verdetto",
  	SignificatoInverso: "Insistere per avere l'ultima parola, Ostentare le proprie capacità intellettuali, Parlare \"sopra le teste\" degli altri, Indugiare su una decisione importante, Cambiare costantemente idea, Rifiutarsi di fare scelte che siano nel proprio interesse, Desiderare invano di poter ritrattare ciò che è stato detto",
  	BreveDescrizione: "Esprimersi con fermezza e autorità, Prendere una decisione definitiva, Consultare un esperto"
  },
  {
  	Titolo: "Asso di Bastoni",
  	Numerologia: "1",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "desiderio, ispirazione, visione, creazione, invenzione",
  	SignificatoInverso: "Non riuscire a sfruttare una grande opportunità, Essere inefficaci o pigri, Fare un Sforzo inadeguato, Lavorare per raggiungere un obiettivo, ma non avere le risorse o l'iniziativa per raggiungere il successo, Fissare obiettivi inappropriati, Non riuscire a prendere posizione",
  	BreveDescrizione: "Essere ispirati, Identificare un obiettivo importante, Avere l'opportunità di fare tutto ciò che si desidera"
  },
  {
  	Titolo: "Due di Bastoni",
  	Numerologia: "2",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "conflitto, decisione, opzione, individualità",
  	SignificatoInverso: "Travisare le proprie intenzioni, Fare una cosa desiderandone un'altra, Cambiare rotta a metà strada senza una buona ragione, Rifiutarsi di cambiare il proprio obiettivo anche quando perseguirlo non ha più senso, Ignorare il contributo degli altri",
  	BreveDescrizione: "Avere una scelta, Offrire o ricevere un'opzione, Vedere il valore dell'approccio di un'altra persona"
  },
  {
  	Titolo: "Tre di Bastoni",
  	Numerologia: "3",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "implementazione, azione, esplorazione",
  	SignificatoInverso: "Procrastinare, Sapere cosa fare, ma rifiutarsi di farlo, Lanciare un progetto senza una chiara definizione di chi dovrebbe fare cosa, Rifiutare l'opportunità di provare qualcosa di nuovo, Non riuscire a finire ciò che si inizia",
  	BreveDescrizione: "Mettere in atto un piano, Fare quel primo passo fondamentale, Far accadere cose buone"
  },
  {
  	Titolo: "Quattro di Bastoni",
  	Numerologia: "4",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "celebrazione, giubilo, comunità, lavoro di squadra, completamento",
  	SignificatoInverso: "Tenere il naso sulla mola, Riconoscere il buon lavoro chiedendone di più, Non partecipare a una celebrazione di gruppo, Permettere all'uva acerba di avvelenare il tuo momento di gloria, Rifiutarsi di fare la propria parte",
  	BreveDescrizione: "Condividere in Una grande festa, Condividere un senso comune di realizzazione e successo, Prepararsi per una festa"
  },
  {
  	Titolo: "Cinque di Bastoni",
  	Numerologia: "5",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "confronto, rottura, distinzione, obiezione, conflitto",
  	SignificatoInverso: "Rimproverare gli altri per le loro opinioni ridicole, Attaccare, Offrire critiche distruttive, Aizzare le persone con commenti pungenti, Interrompere il progresso con un flusso infinito di obiezioni inutili",
  	BreveDescrizione: "Esprimere con calma un'opinione dissenziente, Permettere a qualcuno di usare i propri metodi per portare a termine un lavoro, Aprire la discussione o il dibattito"
  },
  {
  	Titolo: "Sei di Bastoni",
  	Numerologia: "6",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "vittoria, realizzazione, successo, trionfo",
  	SignificatoInverso: "Essere un pessimo vincitore, Permettere ai propri successi di gonfiare il proprio ego, Guardare dall'alto in basso le persone che sembrano meno capaci, Desiderare essere al centro dell'attenzione, Dare o ricevere elogi insinceri, Invidiare i successi degli altri",
  	BreveDescrizione: "Superare i propri pari, Vincere una competizione, Essere riconosciuti come persone capaci"
  },
  {
  	Titolo: "Sette di Bastoni",
  	Numerologia: "7",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "coraggio, risolutezza, determinazione",
  	SignificatoInverso: "Avere un risentimento, Correre rischi inutili per dimostrare la propria impavidità, Cercare un'opportunità per offendersi, Rispondere alle critiche costruttive con atteggiamento difensivo, Rifiutarsi di difendere se stessi e le proprie convinzioni",
  	BreveDescrizione: "Rifiutarsi di essere messi a tacere dalla paura o dall'intimidazione, Continuare a lottare contro ogni previsione, Essere feroci"
  },
  { 
  	Titolo: "Otto di Bastoni", 
  	Numerologia: "8", 
  	Elementi: [], 
  	Lettura: "", 
  	Chakra: "", 
  	PianetaOroscopo: "", 
  	Significato: "velocità, rapidità, reattività, cambiamento", 
  	SignificatoInverso: "Cedersi al panico, Correre in tondo e urlare, Insistere affinché le cose restino sempre le stessee, Mescolare le carte solo per vedere cosa succederà, Mettere fretta agli altri, Rifiutarsi di rivalutare un programma o una tabella di marcia, anche quando chiaramente non è più appropriato",
  	BreveDescrizione: "Agire rapidamente, Andare avanti con un piano il più velocemente possibile, Darsi energia"
  },
  {
  	Titolo: "Nove di Bastoni",
  	Numerologia: "9",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "durezza, persistenza, resistenza, lealtà, liberazione",
  	SignificatoInverso: "Farsi un martire, Abbandonare il proprio incarico, Arrendersi al primo segno di opposizione, Essere impediti di adempiere a un obbligo, Non essere affidabili, Rifiutarsi di lasciar andare qualcosa che deve essere lasciato andare, Percuotere un cavallo morto",
  	BreveDescrizione: "Perseverare per tutta la durata, Mantenere le promesse e gli obblighi, Sopportare una pressione incredibile"
  },
  {
  	Titolo: "Dieci di Bastoni",
  	Numerologia: "10",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "esaurimento, resistenza, peso, oppressione",
  	SignificatoInverso: "Accettare più lavoro di quanto si pensi di poter gestire, Rifiutarsi di dire no, quando si è già sovraccarichi, Prendere l'abitudine di fare gli straordinari, Proteggere gli altri dalle conseguenze del loro scarso giudizio, Sforzarsi troppo regolarmente",
  	BreveDescrizione: "Resistere in circostanze estreme, Aiutare gli altri a portare i loro fardelli, Venire in aiuto degli oppressi"
  },
  {
  	Titolo: "Fante di Bastoni",
  	Numerologia: "11",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "entusiasmo, ansia, fiducia, convalida, affermazione",
  	SignificatoInverso: "Basare la propria intera immagine di sé su ciò che gli altri Pensare, Cogliere ogni nuova idea che ti viene in mente senza porsi domande, Screditare abitualmente input o feedback altrui, Essere così desiderosi di 'fare da soli' da ostacolare il tuo stesso progresso",
  	BreveDescrizione: "Cogliere al volo una nuova opportunità, Essere un sostenitore o un ardente sostenitore della propria causa, Essere un vero credente"
  },
  {
  	Titolo: "Cavaliere di Bastoni",
  	Numerologia: "12",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "audacia, spavalderia, passione, persuasione, difesa",
  	SignificatoInverso: "Avanzare goffamente con competenze o informazioni inadeguate, Calpestare i sentimenti degli altri, Usare il sex appeal per manipolare gli altri, Imporre la propria leadership o ideologia agli altri, Iniziare molti progetti senza portarne a termine nessuno",
  	BreveDescrizione: "Andare avanti a tutta velocità, Fare rapidi progressi, Rifiutare i limiti"
  },
  {
  	Titolo: "Regina di Bastoni",
  	Numerologia: "13",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "attenzione, attrazione, unificazione, collaborazione",
  	SignificatoInverso: "Essere distratti o usare il proprio fascino o le proprie capacità per distrarre gli altri dall'obiettivo, Attirare l'attenzione su di sé con comportamenti negativi o malsani, Interrompere le attività di gruppo come mezzo per alimentare il proprio ego",
  	BreveDescrizione: "Prestare molta attenzione, Aiutare gli altri a concentrarsi sul problema in questione, Far sì che tutti lavorino insieme"
  },
  {
  	Titolo: "Re di Bastoni",
  	Numerologia: "14",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "creatività, ingegno, successo, direzione",
  	SignificatoInverso: "Usare la propria creatività per sottrarsi al lavoro onesto, Investire grandi energie nell'evitare le responsabilità, Vantarsi dei propri successi senza mettere a frutto le proprie competenze, Spadroneggiare sugli altri",
  	BreveDescrizione: "Mettere insieme cose vecchie in modi nuovi ed entusiasmanti, Trovare soluzioni inaspettate, Usare la propria esperienza per risolvere enigmi e problemi"
  },
  {
  	Titolo: "Asso di Denari",
  	Numerologia: "1",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "salute, ricchezza, praticità, ricevere",
  	SignificatoInverso: "Indulgere in un consumismo implacabile, Voler di più, non importa quanto si abbia, Ossessionarsi sul saldo del proprio conto, Soffrire di ipocondria, Consumare benedizioni senza esprimere gratitudine, Prendere ciò che si desidera senza preoccuparsi dei bisogni degli altri",
  	BreveDescrizione: "Delineare un piano per raggiungere la prosperità, Prendere coscienza delle opportunità per migliorare il reddito o la salute, Rendersi conto di avere tutto ciò di cui si ha bisogno"
  },
  {
  	Titolo: "Due di Denari",
  	Numerologia: "2",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "valutazione, decisione, budget, diagnosi",
  	SignificatoInverso: "Impegnarsi in un infinito confronto di prezzi, Rimandare una decisione d'acquisto per paura di trovare un valore leggermente migliore in seguito, Acquistare qualcosa senza considerare il valore, Sforare il budget con spese inutili, Adottare comportamenti senza riguardo per il proprio corpo o per le proprie gambe",
  	BreveDescrizione: "Valutare le opzioni, Confrontare i prezzi, Determinare il valore di un'opzione rispetto a un'altra"
  },
  {
  	Titolo: "Tre di Denari",
  	Numerologia: "3",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "espressione, produzione, lavoro, contributo",
  	SignificatoInverso: "Accostarsi ai gusti degli altri, Non mantenere ciò che si è promesso, Non dare il massimo se non sotto stretta supervisione, Ignorare o rompere gli accordi con chi ha investito in te, Rifiutarsi di fare la propria parte, Non rispettare un accordo chiaramente definito con te stesso o con gli altri",
  	BreveDescrizione: "Completare un progetto, Stabilire e rispettare gli standard, Eseguire secondo le specifiche"
  },
  {
  	Titolo: "Quattro di Denari",
  	Numerologia: "4",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "protezione, conservazione, preservazione, sicurezza",
  	SignificatoInverso: "Essere avari, Rifiutarsi di spendere soldi che devono essere spesi, Trattenere il sesso dal proprio partner, Prendersi cura esclusivamente dei propri bisogni, senza riguardo per quelli degli altri, Spendere un dollaro per risparmiare un centesimo, Non riuscire a gestire bene le benedizioni ricevute",
  	BreveDescrizione: "Risparmiare per un giorno di pioggia, Digiunare come parte di una pratica spirituale, Seguire una dieta nel tentativo di migliorare il proprio corpo"
  },
  {
  	Titolo: "Cinque di Denari",
  	Numerologia: "5",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "povertà, indigenza, bisogno, crisi",
  	SignificatoInverso: "Esagerare i propri bisogni finanziari o fisici, Adottare una mentalità di povertà, Rifiutarsi di sostenersi, Rifiutare offerte di sostegno, Fare il martire, Rifiutare opportunità per migliorare la propria salute o finanze, crogiolarsi nella miseria",
  	BreveDescrizione: "Riconoscere i propri bisogni e agire per soddisfarli, fare tutto il possibile con il poco che si ha, ammettere di aver bisogno di aiuto"
  },
  {
  	Titolo: "Sei di Denari",
  	Numerologia: "6",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "carità, equità, cooperazione, condivisione",
  	SignificatoInverso: "Fare un prestito come mezzo per ottenere il controllo su qualcuno, usare atti di beneficenza per attirare l'attenzione su di sé, dividere il lavoro o le risorse in modo ingiusto, non fare la propria parte in uno sforzo di gruppo, ignorare obblighi e impegni",
  	BreveDescrizione: "Dedicare tempo, denaro o sforzi a un ente di beneficenza, partecipare a uno sforzo di gruppo, prestare le proprie risorse ad altri senza aspettarsi nulla in cambio"
  },
  {
  	Titolo: "Sette di Denari",
  	Numerologia: "7",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "valutazione, rivalutazione, riflessione",
  	SignificatoInverso: "Lasciarsi distrarre da pensieri malinconici, Rimpiangere i 'bei vecchi tempi', Colpevolizzarsi per le opportunità perse, Giudicare severamente il proprio lavoro, Richiedere agli altri standard inappropriati, Rifiutarsi di partecipare a un progetto, per poi lamentarsi della qualità del risultato",
  	BreveDescrizione: "Misurare i progressi verso il proprio obiettivo, Guardare ai risultati con l'obiettivo di migliorare le prestazioni, Chiedersi: 'Quanto sono felice?'"
  },
  {
  	Titolo: "Otto di Denari",
  	Numerologia: "8",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "sforzo, diligenza lavorativa, abilità",
  	SignificatoInverso: "Lavorare fino allo sfinimento, Fare un lavoro svogliato o sciatto, Continuare a fare un lavoro che odi, Comprare regali senza pensarci, Produrre un lavoro con scarsa abilità, Affrettarsi nel lavoro, Rifiutare le opportunità di imparare di più sulla propria arte",
  	BreveDescrizione: "Fare del proprio meglio, Portare entusiasmo e zelo al proprio lavoro, Sforzarsi di essere il meglio che si può essere"
  },
  {
  	Titolo: "Nove di Denari",
  	Numerologia: "9",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "allenamento, disciplina, fiducia, sufficiente",
  	SignificatoInverso: "Essere assegnati a un compito senza essere formati per svolgerlo, Perseguire una posizione per la quale non si è qualificati, Trascurare i requisiti, Rifiutarsi di dedicare tempo o attenzione adeguati quando si impara qualcosa o qualcuno di nuovo, Desiderare sempre di più",
  	BreveDescrizione: "Investire tempo nell'apprendimento o nell'insegnamento di un compito difficile, Astenersi dagli eccessi fisici o finanziari, Fare sacrifici come mezzo per raggiungere obiettivi più grandi"
  },
  {
  	Titolo: "Dieci di Denari",
  	Numerologia: "10",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "ricchezza, abbondanza, acquisizione, avidità",
  	SignificatoInverso: "Spendere tutti i propri soldi in regali e beni stravaganti, Cercare di impressionare gli altri con la propria ricchezza o il proprio aspetto fisico, Fare un regalo eccessivamente costoso come mezzo per accattivarsi la fiducia vor, Ossessionarsi su questioni di peso, salute o finanze, Chiedersi sempre: 'Cosa ci guadagno'",
  	BreveDescrizione: "Celebrare le proprie benedizioni fisiche e finanziarie, Rendersi conto di quanto si è fortunati o benedetti, Essere soddisfatti dei propri successi fisici e finanziari"
  },
  {
  	Titolo: "Fante di Denari",
  	Numerologia: "11",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "praticità, prosperità, apprendimento, crescita, adolescenza",
  	SignificatoInverso: "Cercare di apparire più sani o più ricchi di quanto si sia realmente, Spendere soldi con noncuranza, Vivere rigorosamente per il presente, senza pensare al futuro, Avere atteggiamenti immaturi nei confronti del sesso e della sessualità, Usare la ricchezza o la bellezza come scusa per non dover imparare e crescere",
  	BreveDescrizione: "Imparare il valore di un dollaro, Iniziare un piano di risparmio, Fare i primi passi per uscire dai debiti"
  },
  {
  	Titolo: "Cavaliere di Denari",
  	Numerologia: "12",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "prudenza, concentrazione, realismo, invenzione",
  	SignificatoInverso: "Gettare la cautela ai quattro venti, Spendere senza pensare alle conseguenze, Spendere nel lusso quando mancano le necessità, Sfuggire allo stress spendendo denaro, Ossessionarsi su piccoli dettagli fisici o finanziari, Rincorrere perennemente qualche nuovo gingillo, Copiare il lavoro di un altro e rivendicarlo come proprio",
  	BreveDescrizione: "Spendere denaro saggiamente, Risparmiare per i giorni difficili, Prestare molta attenzione ai dettagli fisici o finanziari"
  },
  {
  	Titolo: "Regina di Denari",
  	Numerologia: "13",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "lusso, comfort, intraprendenza, generosità, prosperità",
  	SignificatoInverso: "Indulgere nella gola o nell'avidità, Diventare insaziabili, Smorzare l'impatto dei piaceri concedendosene troppo spesso, Offrire conforto fisico senza provvedere ai bisogni emotivi, Permettere a un senso di diritto di distorcere la gratitudine per ciò che ci viene dato",
  	BreveDescrizione: "Apprezzare il buon cibo, il buon vino, la bella arte, i bei corpi o qualsiasi altra cosa bella della vita, Godersi una sana sessualità, Viziarsi"
  },
  {
  	Titolo: "Re di Denari",
  	Numerologia: "14",
  	Elementi: [],
  	Lettura: "",
  	Chakra: "",
  	PianetaOroscopo: "",
  	Significato: "stabilità, affidabilità, sicurezza, intervento",
  	SignificatoInverso: "Diventare così conservatori da resistere a ogni cambiamento solo per principio, Ignorare le innovazioni in nome della conservazione della tradizione, Essere presuntuosi o arroganti, Diventare spietatamente dediti al profitto o al piacere, Essere sessualmente egoisti, Comandare gli altri, soprattutto quando non lo sei autorizzato a farlo",
  	BreveDescrizione: "Liberarsi dai debiti, Avere più che abbastanza per sopravvivere, Contribuire a un piano di risparmio"
  }
];