export const carteTarocchi = [
  {
    Titolo: "Il Matto",
    Numerologia: "0",
    Elementi: ["Aria"],
    Lettura: "",
    Chakra: "Corona",
    PianetaOroscopo: "Urano",
    Significato: "freedom, faith, inexperience, innocence",
    SignificatoInverso: "Being gullible and naive, Taking unnecessary risks, Failing to be serious when required, Being silly or distracted, Lacking experience, Failing to honor well-established traditions and limits, Behaving inappropriately",
    BreveDescrizione: "Freeing yourself from limitation, Expressing joy and youthful vigor, Being open-minded"
  },
  {
    Titolo: "Il Mago",
    Numerologia: "1",
    Elementi: ["Mercurio"],
    Lettura: "",
    Chakra: "Gola",
    PianetaOroscopo: "Mercurio",
    Significato: "capability, empowerment, activity",
    SignificatoInverso: "Inflating your own ego, Abusing talents, Manipulating or deceiving others, Being too aggressive, Using cheap illusions to dazzle others, Refusing to invest the time and effort needed to master your craft, Taking shortcuts",
    BreveDescrizione: "Taking appropriate action, Receiving guidance from a higher power, Becoming a channel of divine will"
  },
  {
    Titolo: "La Papessa",
    Numerologia: "2",
    Elementi: ["Acqua", "Luna"],
    Lettura: "",
    Chakra: "Terzo Occhio",
    PianetaOroscopo: "Luna",
    Significato: "intuition, reflection, purity, initiation",
    SignificatoInverso: "Being aloof, Obsessing on secrets and conspiracies, Rejecting guidance from spirit or intuition, Revealing all, Ignoring gut feelings, Refusing to become involved, even when involvement is appropriate",
    BreveDescrizione: "Listening to your feelings and intuitions, Exploring unconventional spirituality, Keeping secrets"
  },
  {
    Titolo: "L'Imperatrice",
    Numerologia: "3",
    Elementi: ["Terra","Venere"],
    Lettura: "",
    Chakra: "Cuore",
    PianetaOroscopo: "Venere",
    Significato: "fertility, productivity, ripeness, nurturing",
    SignificatoInverso: "Overindulging, Being greedy, Smothering someone with attention, Debilitating someone by being overprotective, Inhibiting productivity by obsessing on productivity, Being overcome by addictive behavior",
    BreveDescrizione: "Nurturing yourself and others, Bearing fruit, Celebrating your body"
  },
  {
    Titolo: "L'Imperatore",
    Numerologia: "4",
    Elementi: ["Fuoco","Ariete"],
    Lettura: "",
    Chakra: "Plesso Solare",
    PianetaOroscopo: "Marte",
    Significato: "authority, regulation, direction, structure",
    SignificatoInverso: "Micromanaging, Crushing the creativity of others with a rigid, iron-fisted approach, Insisting on getting your own way, Assuming a dictatorial mindset, Using overt force to achieve your goals and maintain order",
    BreveDescrizione: "Exercising authority, Defining limits, Directing the flow of work"
  },
  {
    Titolo: "Il Papa",
    Numerologia: "5",
    Elementi: ["Terra","Toro"],
    Lettura: "",
    Chakra: "Gola",
    PianetaOroscopo: "Giove",
    Significato: "guidance, knowledge, revelation, belief",
    SignificatoInverso: "Using experience as a means of manipulating or misguiding others, Being dogmatic, Favoring tradition over what is expedient or necessary, Going through the motions of empty rituals, Concealing wisdom, Restricting access to spiritual truths or the gods",
    BreveDescrizione: "Teaching or guiding others, Searching for the truth, Asking for guidance from a higher power"
  },
  {
    Titolo: "Gli Amanti",
    Numerologia: "6",
    Elementi: ["Aria","Gemelli"],
    Lettura: "",
    Chakra: "Cuore",
    PianetaOroscopo: "Venere",
    Significato: "love, passion, unity, choice",
    SignificatoInverso: "Debilitating passion, Allowing an unhealthy desire for love to motivate destructive behavior, Disrupting unity, Working against the best interests of those who care about you, Ill-informed decisions",
    BreveDescrizione: "Being in love, Showing your love to others, Expressing passion or romantic feelings"
  },
  {
    Titolo: "Il Carro",
    Numerologia: "7",
    Elementi: ["Acqua","Cancro"],
    Lettura: "",
    Chakra: "Plesso Solare",
    PianetaOroscopo: "Luna",
    Significato: "advancement, victory, triumph, success",
    SignificatoInverso: "Resting on laurels, Riding roughshod over the feelings or expectations of others, Focusing more on past successes than future opportunities, Failing to rein in impulsive behavior",
    BreveDescrizione: "Breaking through barriers, Moving forward with confidence and authority, Reaching the pinnacle of success"
  },
  {
    Titolo: "La Forza",
    Numerologia: "8",
    Elementi: ["Fuoco","Leone"],
    Lettura: "",
    Chakra: "Cuore",
    PianetaOroscopo: "Sole",
    Significato: "discipline, boldness, self-discipline, power, vitality",
    SignificatoInverso: "Indulging weakness, even when you know it will damage your health and happiness, Languishing in addiction, Allowing your instincts to tame and conquer you, Failing to take a stand when necessary",
    BreveDescrizione: "Imposing restrictions on yourself for your own benefit, Bringing your passions under the control of reason, Resisting impulses that work against your best interests"
  },
  {
    Titolo: "L'Eremita",
    Numerologia: "9",
    Elementi: ["Terra","Vergine"],
    Lettura: "",
    Chakra: "Terzo Occhio",
    PianetaOroscopo: "Mercurio",
    Significato: "solitude, experience, stillness, withdrawal",
    SignificatoInverso: "Being a loner, Fearing contact with others, Becoming a know-it-all, Inflating claims of expertise, Hiding your skills and talents out of fear of unworthiness",
    BreveDescrizione: "Becoming or seeking out a guru, Going on a retreat, Recharging spiritual or creative batteries"
  },
  {
    Titolo: "La Ruota della Fortuna",
    Numerologia: "10",
    Elementi: ["Fuoco","Giove"],
    Lettura: "",
    Chakra: "Corona",
    PianetaOroscopo: "Giove",
    Significato: "luck, randomness, cycles, karma, fate, revolution",
    SignificatoInverso: "Losing money gambling, Refusing to do your part to bring a plan to fruition, Taking a fatalistic approach to life, Fighting the natural course of events",
    BreveDescrizione: "Allowing events to unfold, Seeing the larger pattern in everyday events, Trusting your luck"
  },
  {
    Titolo: "La Giustizia",
    Numerologia: "11",
    Elementi: ["Aria","Bilancia"],
    Lettura: "",
    Chakra: "Cuore",
    PianetaOroscopo: "Venere",
    Significato: "balance, law, fairness, objectivity",
    SignificatoInverso: "Delivering harsh criticism, Obsessing on rules and regulations, Playing by the book even when it is destructive or counterproductive to do so, Confusing snap decisions with timely action, Playing favorites",
    BreveDescrizione: "Making an objective decision, Weighing an issue carefully before taking action, Appropriately scaling your reaction to a situation"
  },
  {
    Titolo: "L'Appeso",
    Numerologia: "12",
    Elementi: ["Acqua"],
    Lettura: "",
    Chakra: "Plesso Solare",
    PianetaOroscopo: "Nettuno",
    Significato: "enlightenment, sacrifice, perspective, suspension, reversals",
    SignificatoInverso: "Being untrue to yourself and your values, Refusing to make sacrifices when appropriate, Refusing to adapt to new situations, Blaming others, Profiting at the expense of others",
    BreveDescrizione: "Seeing growth opportunities in unpleasant events, Experiencing a dramatic change in personal perspective, Making the best of an unforeseen change in your life or work"
  },
  {
    Titolo: "La Morte",
    Numerologia: "13",
    Elementi: ["Acqua","Scorpione"],
    Lettura: "",
    Chakra: "Plesso Solare",
    PianetaOroscopo: "Plutone",
    Significato: "ending, conclusion, transition, passage, departure",
    SignificatoInverso: "Obsessing on death and dying, Refusing to give up old habits or unhealthy relationships, Insisting that everything and everyone should stay the same forever, Failing to take good care of yourself",
    BreveDescrizione: "Bringing an unpleasant phase of life to an end, Recognizing and celebrating the conclusion of something, Putting bad habits to rest"
  },
  {
    Titolo: "La Temperanza",
    Numerologia: "14",
    Elementi: ["Fuoco","Sagittario"],
    Lettura: "",
    Chakra: "Cuore",
    PianetaOroscopo: "Giove",
    Significato: "blending, synthesis, mediation, combination, harmony",
    SignificatoInverso: "Going to extremes, Disrupting group efforts, Ignoring healthy approaches to life, Becoming an addict, Practicing gluttony, Tearing something or someone apart, Breaking alliances",
    BreveDescrizione: "Bringing opposites together, Moderating your actions or emotions, Finding middle ground"
  },
  {
    Titolo: "Il Diavolo",
    Numerologia: "15",
    Elementi: ["Terra","Capricorno"],
    Lettura: "",
    Chakra: "Radice",
    PianetaOroscopo: "Saturno",
    Significato: "shadow, materialism, bondage, delusion",
    SignificatoInverso: "Putting excessive emphasis on appearances, Always wanting more, Valuing possessions more than people or relationships, Allowing base instincts to govern your life, Being selfish, Attributing your own dark impulses to outside forces or other people",
    BreveDescrizione: "Appreciating the luxuries that life has to offer, Being comfortable in your own skin, Enjoying your sexuality"
  },
  {
    Titolo: "La Torre",
    Numerologia: "16",
    Elementi: ["Fuoco","Marte"],
    Lettura: "",
    Chakra: "Plesso Solare",
    PianetaOroscopo: "Marte",
    Significato: "demolition, upheaval, deconstruction, disaster, destruction",
    SignificatoInverso: "Clinging to traditions that repress growth, Engaging in willful blindness, Rejecting evidence that change is needed, Ignoring guidance from a higher power, Maliciously engaging in destructive behavior",
    BreveDescrizione: "Breaking out of old, confining habits and mindsets, Clearing the way for new growth, Dispelling the influence of an inflated ego"
  },
  {
    Titolo: "La Stella",
    Numerologia: "17",
    Elementi: ["Aria","Acquario"],
    Lettura: "",
    Chakra: "Terzo Occhio",
    PianetaOroscopo: "Urano",
    Significato: "hope, optimism, openness, certainty, faith, longing, truth",
    SignificatoInverso: "Denying unpleasant truths, Denying personal accountability and saying, \"Things just happen!\", Ignoring signs and omens, Preferring illusion to reality, Spreading pessimism and stinginess of spirit",
    BreveDescrizione: "Hoping for the best, Believing good things happen to good people, Seeing events in the best possible light"
  },
  {
    Titolo: "La Luna",
    Numerologia: "18",
    Elementi: ["Acqua","Pesci"],
    Lettura: "",
    Chakra: "Terzo Occhio",
    PianetaOroscopo: "Nettuno",
    Significato: "mystery, fantasy, imagination, dreams, uncertainty",
    SignificatoInverso: "Becoming unable to separate fantasy from reality, Suffering from delusions, Losing your appreciation for the fantastic or magical, Adopting a ruthlessly logical mindset, Failing to appreciate life's mysteries",
    BreveDescrizione: "Enjoying healthy fantasies and daydreams, Using your imagination, Practicing magic or celebrating the magic of everyday life"
  },
  {
    Titolo: "Il Sole",
    Numerologia: "19",
    Elementi: ["Fuoco","Sole"],
    Lettura: "",
    Chakra: "Plesso Solare",
    PianetaOroscopo: "Sole",
    Significato: "joy, brilliance, validation, attention, energy",
    SignificatoInverso: "Being dazzled by your own accomplishments, Becoming absorbed in your own self-image, Feeling rushed and distracted, Exerting yourself to the point of exhaustion, Overstating your abilities or misrepresenting your achievements",
    BreveDescrizione: "Seeing things clearly, Experiencing intense joy, Celebrating your own successes"
  },
  {
    Titolo: "Il Giudizio",
    Numerologia: "20",
    Elementi: ["Fuoco"],
    Lettura: "",
    Chakra: "Corona",
    PianetaOroscopo: "Plutone",
    Significato: "revival, renewal, resurrection, evaluation, invitation",
    SignificatoInverso: "Being weighed in the balances and found wanting, Failing to measure up to a well-defined standard, Being caught goofing off or misbehaving, Failing to prepare for an examination you know is coming, Rejecting an opportunity to reinvent yourself",
    BreveDescrizione: "Receiving a wake-up call, Discovering a new purpose in life, Becoming totally and completely yourself"
  },
  {
    Titolo: "Il Mondo",
    Numerologia: "21",
    Elementi: ["Terra","Saturno"],
    Lettura: "",
    Chakra: "Radice",
    PianetaOroscopo: "Saturno",
    Significato: "wholeness, integration, totality, completeness, fullness",
    SignificatoInverso: "Allowing greed and envy to prevent you from enjoying what you do possess, Failing to see the larger design in ordinary events, Believing that everything that exists can be touched, counted, or measured, Failing to see the divine reflected in those around you",
    BreveDescrizione: "Having it all, Knowing and loving yourself as completely as possible, Seeing the interconnection of all things and people"
  },
  {
    Titolo: "Asso di Coppe",
    Numerologia: "1",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "intuition, spirituality, affection, motivation",
    SignificatoInverso: "Hiding your feelings, Spurning an opportunity to love or be loved, Numbing yourself to spiritual yearnings, Rejecting the counsel of your heart, Becoming a puppet of your own emotions, Indulging in hysteria or obsession",
    BreveDescrizione: "Trusting your feelings, Opening yourself to spirit, Accepting and returning affection"
  },
  {
    Titolo: "Due di Coppe",
    Numerologia: "2",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "union, attraction, combination, affection",
    SignificatoInverso: "Burning bridges, Becoming caught up in unhealthy codependency, Shutting out anyone but your chosen few, Obsessing on someone who does not return your affections, Despairing over finding \"The One\", Deceiving yourself about your true orientation",
    BreveDescrizione: "Being drawn to someone, Longing for someone or something, Acting on your desires"
  },
  {
    Titolo: "Tre di Coppe",
    Numerologia: "3",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "celebration, expression, community, friendliness",
    SignificatoInverso: "Mistaking giddiness for true affection, Being dominated by manic emotions, Expecting everyone to always feel the same way you do, Demanding unreasonable support from friends or family, Partying to a dangerous or unhealthy extent",
    BreveDescrizione: "Celebrating your feelings or connections with others, Expressing joy through song, dance, or physical affection, Working together with others who share your feelings"
  },
  {
    Titolo: "Quattro di Coppe",
    Numerologia: "4",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "boredom, listlessness, lethargy, stability, ingratitude",
    SignificatoInverso: "Being bored, Daydreaming at the expense of your work, Refusing to be engaged by opportunity, Taking people and relationships for granted, Ignoring romantic or spiritual opportunities, Spurning inspiration, Feeling everything should stay \"just like it is\"",
    BreveDescrizione: "Maintaining your emotional stability, Refusing to give in to overwhelming emotions, Appreciating what you have and refusing to take it for granted"
  },
  {
    Titolo: "Cinque di Coppe",
    Numerologia: "5",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "loss, despair, re-evaluation, regret, uncertainty, repentance",
    SignificatoInverso: "Wallowing in unhealthy grief or self-pity, Refusing to move on and let go, Clinging to the past, Obsessing on past lives and past loves, Failing to live in the present, Beating yourself up over past mistakes, Allowing fear of failure to limit your efforts",
    BreveDescrizione: "Acknowledging loss and moving on, Focusing on how the glass remains \"half-full\", Finding the silver lining in a dark cloud"
  },
  {
    Titolo: "Sei di Coppe",
    Numerologia: "6",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "charity, sharing, sacrifice, cooperation, fairness",
    SignificatoInverso: "Linking your sense of self-worth to the appraisals of others, Striving to appear more needy than you really are, Taking undeserved or unmerited charity, Bragging about your charitable efforts, Profiteering in times of distress, Refusing to share a burden",
    BreveDescrizione: "Donating your time and talents to others, Taking satisfaction in knowing how your efforts will aid others, Creating a \"win-win\" scenario"
  },
  {
    Titolo: "Sette di Coppe",
    Numerologia: "7",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "imagination, dreams, illusions, goals",
    SignificatoInverso: "Obsessing on imaginary fears or uncertain consequences, Giving in to emotional or political terrorism, Spending more time dreaming than working, Failing to envision the possible repercussions of your choices, Being controlled by fear",
    BreveDescrizione: "Motivating yourself with images of future success, Using visualization to encourage progress, Taking an imaginative or creative approach to problem solving"
  },
  {
    Titolo: "Otto di Coppe",
    Numerologia: "8",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "longing, dissatisfaction, quest, departure, withdrawal",
    SignificatoInverso: "Being implacable, Finding fault, Nitpicking, Refusing to settle down, Running away from problems or confrontations, Saying, \"It's my way or the highway!\", Harping on past mistakes and disappointments, Threatening to quit as a strategy to get your way",
    BreveDescrizione: "Wanting something better, Blazing your own trail, Realizing there must be more to life"
  },
  {
    Titolo: "Nove di Coppe",
    Numerologia: "9",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "satisfaction, sensuality, luxury, pleasure",
    SignificatoInverso: "Being smug, Satisfying yourself at the expense of others, Being selfish, Over-indulging, Avoiding work that needs to be done, Claiming achievements or skills you do not possess, Never being satisfied, no matter how much you have",
    BreveDescrizione: "Being delighted with your own achievements, Recognizing your own talents and abilities, Reveling in the good things life has to offer"
  },
  {
    Titolo: "Dieci di Coppe",
    Numerologia: "10",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "joy, fulfillment, overwhelming emotion, giddiness",
    SignificatoInverso: "Comparing your achievements or relationships to unrealistic fantasy standards, Experiencing emotions so intense they blunt your ability to cope with reality, Feeling overwhelmed, Envying the achievements and happiness of others",
    BreveDescrizione: "Having more than you ever dreamed, Being deeply thankful for all you've been given, Recognizing the Hand of God in the gifts the Universe brings your way"
  },
  {
    Titolo: "Fante di Coppe",
    Numerologia: "11",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "enthusiasm, first impressions, romanticism, superficiality",
    SignificatoInverso: "Mistaking a crush for true love, Reading romantic intention into innocent action, Frantically trying to impress others, Indulging in overly-sweet sentimentality, Pretending to more romantic or spiritual experience than you possess",
    BreveDescrizione: "Showing your emotions freely, Throwing yourself into romance, Nursing a secret crush"
  },
  {
    Titolo: "Cavaliere di Coppe",
    Numerologia: "12",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "fervor, zeal, moodiness, illumination",
    SignificatoInverso: "Becoming a fanatic, Rejecting information that suggests your intuitions are misguided, Allowing your emotions to control you, Giving in to jealousy, confrontation, and peer pressure, Hiding or ignoring intuitive insights",
    BreveDescrizione: "Being deeply committed to a cause, Giving in to strong emotions, from excitement to depression, Acting on intuition alone"
  },
  {
    Titolo: "Regina di Coppe",
    Numerologia: "13",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "insightfulness, spirituality, compassion, empathy, instinct",
    SignificatoInverso: "Becoming so caught up in matters of Spirit, you become detached from the world, Allowing empathy to disable you (instead of inspire action), Using psychic abilities to wield covert influence, Wallowing in emotionalism, sentiment, or self-pity",
    BreveDescrizione: "Allowing yourself to be moved by the plight of others, Feeling strong emotions, Possessing unusual sympathy or empathy"
  },
  {
    Titolo: "Re di Coppe",
    Numerologia: "14",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "wisdom, diplomacy, restraint, composure",
    SignificatoInverso: "Allowing yourself to become rigid and unemotional, Making unfair decisions based on a hidden agenda, Making decisions without regard for their emotional impact on others, Abusing spiritual authority, Using emotional or spiritual leverage to exercise unhealthy control over others",
    BreveDescrizione: "Keeping a stiff upper lip, Being brave and clear in the face of adverse circumstances, Sharing experience as a way of comforting others"
  },
  {
    Titolo: "Asso di Spade",
    Numerologia: "1",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "logic, objectivity, intellect, choice",
    SignificatoInverso: "Applying ruthless or twisted logic, Gloating over your own superior intellect, Using quick thinking to deceive or confuse others, Confusing snap judgments with quick thinking, Making decisions without thinking through consequences",
    BreveDescrizione: "Making objective decisions, Applying logic, Reasoning your way out of a difficult situation"
  },
  {
    Titolo: "Due di Spade",
    Numerologia: "2",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "denial, debate, impasse, truce",
    SignificatoInverso: "Rejecting evidence that conflicts with dearly-held beliefs, Arguing with others just for the sake of doing so, Nit-picking, Putting off a decision because you're afraid to face the consequences, Preventing others from getting the information they need to make good decisions",
    BreveDescrizione: "Refusing to make a decision without getting the facts, Exploring both sides of an argument, Arguing passionately for what you believe in"
  },
  {
    Titolo: "Tre di Spade",
    Numerologia: "3",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "variance, difference, dissatisfaction, heartache, rejection",
    SignificatoInverso: "Wallowing in despair, Allowing yourself to be completely crushed by the thoughts, words, or deeds of another, Judging yourself too harshly, Holding yourself to an unrealistic standard of excellence, Wearing your heart on your sleeve while carrying a chip on your shoulder",
    BreveDescrizione: "Being brave enough to see things as they really are, Exercising your critical eye, Being your own best critic"
  },
  {
    Titolo: "Quattro di Spade",
    Numerologia: "4",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "meditation, contemplation, perspective, mindset",
    SignificatoInverso: "Failing to think things through, Mistaking procrastination for thoughtfulness, Adopting a point of view and refusing to reconsider your conclusions, even when presented with refuting evidence, Allowing chaos and whimsy to dominate your thoughts",
    BreveDescrizione: "Thinking over your plans before putting them into action, Pausing to meditate or clear your mind, Taking time to understand someone or something before criticizing it"
  },
  {
    Titolo: "Cinque di Spade",
    Numerologia: "5",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "selfishness, hostility, irrationality, self-preservation",
    SignificatoInverso: "Taking advantage of others, Intimidating others, Acting in an unethical manner, Picking fights, Using words to goad others into violence and irrationality, Ignoring rules you've agreed to abide by, Looking out for yourself while allowing harm to come to others, Gloating over victory",
    BreveDescrizione: "Acting in your own best interest, Choosing to stand up for yourself, Not backing down from disagreement and discord"
  },
  {
    Titolo: "Sei di Spade",
    Numerologia: "6",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "adaptation, adjustments, science, travel",
    SignificatoInverso: "Refusing to accept that things have changed, Playing the victim, Rejecting the idea that your actions have consequences, Applying scientific criteria to matters of faith, or confusing faith with science, Believing the whole world should be like your small corner of it",
    BreveDescrizione: "Making the best of a bad situation, Recovering from defeat, Resetting expectations"
  },
  {
    Titolo: "Sette di Spade",
    Numerologia: "7",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "dishonesty, presumption, sneakiness, assumptions",
    SignificatoInverso: "Stealing or lying, Doing whatever you can get away with, simply because you can, Looking for a way around consequences, Justifying wicked behavior by focusing on the wickedness of others, Failing to examine your own motives and prejudices",
    BreveDescrizione: "Refusing to do something dishonest, even when there's no chance of ever being caught, Handling a difficult situation with finesse, Pointing out assumptions"
  },
  {
    Titolo: "Otto di Spade",
    Numerologia: "8",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "restriction, limitation, confinement, helplessness",
    SignificatoInverso: "Feeling trapped, Being lost in a maze of rules and regulations, Giving in to despair, Playing the victim, Allowing others to dictate what you can and cannot do, Being rendered helpless, Having very few options, Failing to look for a way out",
    BreveDescrizione: "Honoring limits, Respecting the rules, Deciding to go on a diet for your health's sake"
  },
  {
    Titolo: "Nove di Spade",
    Numerologia: "9",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "remorse, worry, distraught, conclusion",
    SignificatoInverso: "Torturing yourself with regrets, Second-guessing your every move, Beating yourself up for your mistakes, Depression, Obsessing on errors and overlooked details, Refusing to handle stress in healthy ways, Ruining your ability to appreciate the present by dwelling on the past, Debating irreversible decisions",
    BreveDescrizione: "Refusing to worry about what you cannot control, Rejecting anxiety, Judging your own performance with kindness and gentleness"
  },
  {
    Titolo: "Dieci di Spade",
    Numerologia: "10",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "exhaustion, ruin, disaster, stamina, obsession",
    SignificatoInverso: "Accepting defeat prematurely, Driving yourself to total exhaustion, especially mentally, Experiencing a mental breakdown, Obsessing on a problem to the breaking point, Giving up, Refusing to move from thought to action, Deeply unhealthy thoughts",
    BreveDescrizione: "Seeing the signs that you've reached your limits, Paying attention to what your body is trying to tell you, Giving in to the need for rest and renewal"
  },
  {
    Titolo: "Fante di Spade",
    Numerologia: "11",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "student, apprentice, scholarship, information",
    SignificatoInverso: "Pretending to knowledge or sophistication you do not possess, Cheating on an exam, Feigning interest as a way of gaining favor, Considering only the evidence that supports conclusions you've already drawn, Rejecting the wise counsel of experienced teachers",
    BreveDescrizione: "Pursuing a course of study, Asking good questions, Investing time in study and practice"
  },
  {
    Titolo: "Cavaliere di Spade",
    Numerologia: "12",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "bluntness, intelligence, incisiveness, investigation",
    SignificatoInverso: "Stating your opinions as fact, Picking fights, Starting arguments, Using clever insults to undermine the confidence of others, Tossing reason out the window, Speaking without taking the feelings of others into account, Going on a witch hunt, Distorting evidence",
    BreveDescrizione: "Speaking your mind, Making your opinions known, Offering constructive criticism"
  },
  {
    Titolo: "Regina di Spade",
    Numerologia: "13",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "grace, skill, wit, charm, aptitude",
    SignificatoInverso: "Knowing exactly what to say to destroy another person, Withholding critical information, Using a barbed tongue to upset others, Employing sarcasm, Mimicking others unkindly, Making light of the less fortunate, Being disrespectful, Failing to use the talent you've been given",
    BreveDescrizione: "Exercising tact or using diplomacy, Defusing a tense situation, Knowing what to say and how to say it"
  },
  {
    Titolo: "Re di Spade",
    Numerologia: "14",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "genius, expertise, decision, verdict",
    SignificatoInverso: "Insisting on having the last word, Flaunting your intellectual capability, Talking \"over the heads\" of others, Waffling on an important decision, Constantly changing your mind, Refusing to make choices that are in your own best interest, Wishing in vain you could take back what's been said",
    BreveDescrizione: "Expressing yourself with firmness and authority, Rendering a final decision, Consulting an expert"
  },
  {
    Titolo: "Asso di Bastoni",
    Numerologia: "1",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "desire, inspiration, vision, creation, invention",
    SignificatoInverso: "Failing to take advantage of a great opportunity, Being ineffectual or lazy, Making an inadequate effort, Working toward a goal, but lacking the resources or initiative to achieve success, Setting inappropriate goals, Failing to take a stand",
    BreveDescrizione: "Being inspired, Identifying an important goal, Being given the opportunity to do whatever you want to do"
  },
  {
    Titolo: "Due di Bastoni",
    Numerologia: "2",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "conflict, decision, option, individuality",
    SignificatoInverso: "Misrepresenting your intentions, Doing one thing while desiring another, Changing course mid-stream for no good reason, Refusing to change your goal even when pursuing it no longer makes sense, Disregarding the input of others",
    BreveDescrizione: "Having a choice, Offering or being offered an option, Seeing the value of another person's approach"
  },
  {
    Titolo: "Tre di Bastoni",
    Numerologia: "3",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "implementation, action, exploration",
    SignificatoInverso: "Procrastinating, Knowing what to do, but refusing to do it, Launching a project without a clear definition of who should do what, Rejecting an opportunity to try something new, Failing to finish what you start",
    BreveDescrizione: "Putting a plan into motion, Taking that critical first step, Making good things happen"
  },
  {
    Titolo: "Quattro di Bastoni",
    Numerologia: "4",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "celebration, jubilation, community, teamwork, completion",
    SignificatoInverso: "Keeping your nose to the grindstone, Recognizing good work by demanding more work, Failing to share in a group celebration, Allowing sour grapes to poison your moment in the sun, Refusing to do your part",
    BreveDescrizione: "Sharing in a great celebration, Sharing in a communal sense of achievement and success, Preparing for a party"
  },
  {
    Titolo: "Cinque di Bastoni",
    Numerologia: "5",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "confrontation, disruption, distinction, objection, strife",
    SignificatoInverso: "Berating others for their ridiculous opinions, Picking fights, Offering destructive criticism, Baiting people with barbed remarks, Disrupting progress with an endless stream of pointless objections",
    BreveDescrizione: "Calmly expressing a dissenting opinion, Allowing someone to use his or her own methods to get a job done, Opening the floor for discussion or debate"
  },
  {
    Titolo: "Sei di Bastoni",
    Numerologia: "6",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "victory, achievement, success, triumph",
    SignificatoInverso: "Being a bad winner, Allowing your achievements to inflate your ego, Looking down on people who seem less capable, Craving to be the center of attention, Giving or receiving insincere praise, Envying the achievements of others",
    BreveDescrizione: "Outperforming your peers, Winning a competition, Being recognized as a capable person"
  },
  {
    Titolo: "Sette di Bastoni",
    Numerologia: "7",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "bravery, resolve, determination",
    SignificatoInverso: "Having a chip on your shoulder, Taking unnecessary risks as a means of proving your fearlessness, Looking for an opportunity to take offense, Responding to constructive criticism with defensiveness, Refusing to stand up for yourself and your beliefs",
    BreveDescrizione: "Refusing to be silenced through fear or intimidation, Continuing a fight against all odds, Being fierce"
  },
  {
    Titolo: "Otto di Bastoni",
    Numerologia: "8",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "speed, swiftness, responsiveness, change",
    SignificatoInverso: "Giving in to panic, Running in circles and screaming, Insisting things must always stay the same, Stirring the pot just to see what will happen, Rushing others, Refusing to re-evaluate a schedule or program, even when it's clearly no longer appropriate",
    BreveDescrizione: "Taking swift action, Moving forward with a plan as quickly as possible, Energizing yourself"
  },
  {
    Titolo: "Nove di Bastoni",
    Numerologia: "9",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "toughness, persistence, stamina, loyalty, release",
    SignificatoInverso: "Making yourself a martyr, Abandoning your post, Giving up at the first sign of opposition, Being prevented from fulfilling an obligation, Failing to be dependable, Refusing to let something go that needs to be released, Beating a dead horse",
    BreveDescrizione: "Sticking with it for the duration, Fulfilling your promises and obligations, Bearing up under incredible duress"
  },
  {
    Titolo: "Dieci di Bastoni",
    Numerologia: "10",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "exhaustion, resistance, burden, oppression",
    SignificatoInverso: "Taking on more work than you know you can handle, Refusing to say \"No\" when you're already overloaded, Making a habit of working overtime, Shielding others from facing the consequences of their own poor judgment, Over-extending yourself on a regular basis",
    BreveDescrizione: "Holding your own in extreme circumstances, Helping others carry their burdens, Coming to the aid of the oppressed"
  },
  {
    Titolo: "Fante di Bastoni",
    Numerologia: "11",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "enthusiasm, eagerness, confidence, validation, affirmation",
    SignificatoInverso: "Basing your entire self-image on what others think, Seizing every new idea that comes your way without question, Habitually discounting input or feedback from others, Being so eager to \"do it yourself\" that you hinder your own progress",
    BreveDescrizione: "Leaping at a new opportunity, Being a cheerleader or ardent advocate for your cause, Being a True Believer"
  },
  {
    Titolo: "Cavaliere di Bastoni",
    Numerologia: "12",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "boldness, bravado, passion, persuasion, advocacy",
    SignificatoInverso: "Blundering forward with inadequate skill or information, Running roughshod over the feelings of others, Using sex appeal to manipulate others, Forcing your leadership or ideology on others, Beginning many projects without finishing any",
    BreveDescrizione: "Charging ahead, Making rapid progress, Refusing limits"
  },
  {
    Titolo: "Regina di Bastoni",
    Numerologia: "13",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "attention, attraction, unification, collaboration",
    SignificatoInverso: "Being distracted, or using your charms or skills to distract others from the goal, Calling attention to yourself with negative or unhealthy behaviors, Disrupting group activities as a means of feeding your own ego",
    BreveDescrizione: "Paying close attention, Helping others focus on the issue at hand, Getting everyone to work together"
  },
  {
    Titolo: "Re di Bastoni",
    Numerologia: "14",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "creativity, ingenuity, achievement, direction",
    SignificatoInverso: "Using your creativity to get out of honest work, Investing great energy in avoiding responsibility, Boasting about achievements without putting your expertise to practical use, Lording it over others",
    BreveDescrizione: "Putting old things together in new and exciting ways, Coming up with unexpected solutions, Using your experience to solve puzzles and problems"
  },
  {
    Titolo: "Asso di Denari",
    Numerologia: "1",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "health, wealth, practicality, receiving",
    SignificatoInverso: "Indulging in relentless consumerism, Wanting more, no matter how much you have, Obsessing on your account balance, Suffering from hypochondria, Consuming blessings without expressing gratitude, Taking what you want without concern for the needs of others",
    BreveDescrizione: "Outlining a plan for achieving prosperity, Becoming aware of opportunities to improve income or health, Realizing you have everything you need"
  },
  {
    Titolo: "Due di Denari",
    Numerologia: "2",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "evaluation, decision, budgeting, diagnosis",
    SignificatoInverso: "Engaging in endless price comparison, Putting off a buying decision for fear of finding a slightly better value later on, Buying something without regard for value, Breaking your budget with unnecessary expenses, Engaging in behavior with no regard for how your body or bankbook will be impacted",
    BreveDescrizione: "Weighing options, Comparing prices, Determining the value of one option over another"
  },
  {
    Titolo: "Tre di Denari",
    Numerologia: "3",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "expression, production, work, contribution",
    SignificatoInverso: "Pandering to the tastes of others, Failing to deliver what you've promised, Not delivering your best work unless closely supervised, Ignoring or breaking agreements with those who have invested in you, Refusing to do your part, Failing to abide by a clearly-outlined agreement with yourself or others",
    BreveDescrizione: "Finishing a project, Setting and meeting standards, Performing according to specifications"
  },
  {
    Titolo: "Quattro di Denari",
    Numerologia: "4",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "protection, conservation, preservation, safety",
    SignificatoInverso: "Being stingy, Refusing to spend money that needs to be spent, Withholding sex from your partner, Taking care of your own needs exclusively, without regard for the needs of others, Spending a dollar to save a penny, Failing to be a good manager of the blessings you've been given",
    BreveDescrizione: "Saving for a rainy day, Fasting as part of a spiritual practice, Dieting in an effort to improve your body"
  },
  {
    Titolo: "Cinque di Denari",
    Numerologia: "5",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "poverty, destitution, need, crisis",
    SignificatoInverso: "Exaggerating your financial or physical needs, Adopting a poverty mentality, Refusing to support yourself, Refusing offers of support, Playing the martyr, Turning down opportunities to improve your health or finances, Wallowing in misery",
    BreveDescrizione: "Recognizing your needs and taking action to fulfill them, Doing as much as you can do with what little you have, Admitting you need help"
  },
  {
    Titolo: "Sei di Denari",
    Numerologia: "6",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "charity, fairness, cooperation, sharing",
    SignificatoInverso: "Making a loan as a means of gaining control over someone, Using charitable acts to draw attention to yourself, Dividing work or resources unfairly, Failing to do your part in a group effort, Ignoring obligations and commitments",
    BreveDescrizione: "Giving time, money, or effort to a charity, Taking part in a group effort, Lending your resources to others without expecting anything in return"
  },
  {
    Titolo: "Sette di Denari",
    Numerologia: "7",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "assessment, evaluation, re-evaluation, reflection",
    SignificatoInverso: "Becoming distracted by melancholy thoughts, Longing for \"the good old days\", Beating yourself up over lost opportunities, Judging your own work harshly, Holding others to inappropriate standards, Refusing to take part in a project, then whining about the quality of the outcome",
    BreveDescrizione: "Measuring progress toward your goal, Looking at results with an eye toward improving performance, Asking, \"How happy am I?\""
  },
  {
    Titolo: "Otto di Denari",
    Numerologia: "8",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "effort, work diligence, skill",
    SignificatoInverso: "Working yourself to death, Doing a half-hearted or sloppy job, Continuing in a job you hate, Buying thoughtless gifts, Producing work with shoddy craftsmanship, Rushing through your work, Rejecting opportunities to learn more about your craft",
    BreveDescrizione: "Doing your best, Bringing enthusiasm and zeal to your work, Making an effort to be the best you can be"
  },
  {
    Titolo: "Nove di Denari",
    Numerologia: "9",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "training, discipline, confidence, enough",
    SignificatoInverso: "Being assigned to a task without being trained to perform it, Pursuing a position for which you are not qualified, Disregarding requirements, Refusing to dedicate adequate time or attention when learning about something or someone new, Always craving more",
    BreveDescrizione: "Investing time in learning or teaching a difficult task, Restraining yourself from physical or financial extremes, Making sacrifices as a way of achieving larger goals"
  },
  {
    Titolo: "Dieci di Denari",
    Numerologia: "10",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "wealth, abundance, acquisition, greed",
    SignificatoInverso: "Spending all of your money on extravagant gifts and possessions, Trying too hard to impress others with your wealth or physique, Giving an inappropriately expensive gift as a means of currying favor, Obsessing on matters of weight, health, or finance, Always asking, \"What's in it for me?\"",
    BreveDescrizione: "Celebrating your physical and financial blessings, Realizing how lucky or how blessed you are, Being satisfied with your physical and financial achievements"
  },
  {
    Titolo: "Fante di Denari",
    Numerologia: "11",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "practicality, prosperity, learning, growth, adolescence",
    SignificatoInverso: "Trying to appear healthier or wealthier than you really are, Spending money carelessly, Living strictly for today, with no thought of tomorrow, Possessing immature attitudes toward sex and sexuality, Using wealth or beauty as an excuse for not having to learn and grow",
    BreveDescrizione: "Learning the value of a dollar, Starting a savings plan, Taking the first steps toward getting out of debt"
  },
  {
    Titolo: "Cavaliere di Denari",
    Numerologia: "12",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "caution, focus, realism, invention",
    SignificatoInverso: "Throwing caution to the four winds, Spending without regard for consequence, Spending on luxury when necessities are lacking, Escaping stress by spending money, Obsessing on tiny physical or financial details, Perpetually chasing after some new bauble, Copying another's work and claiming it as your own",
    BreveDescrizione: "Spending money wisely, Saving for a rainy day, Paying close attention to physical or financial details"
  },
  {
    Titolo: "Regina di Denari",
    Numerologia: "13",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "luxury, comfort, resourcefulness, generosity, prosperity",
    SignificatoInverso: "Indulging in gluttony or greediness, Becoming insatiable, Blunting the impact of treats by indulging in them too often, Providing physical comfort without providing for emotional needs, Allowing a feeling of entitlement to distort your gratitude for what you're given",
    BreveDescrizione: "Appreciating fine food, fine wine, beautiful art, beautiful bodies, or any of the better things in life, Reveling in healthy sexuality, Treating yourself"
  },
  {
    Titolo: "Re di Denari",
    Numerologia: "14",
    Elementi: [],
    Lettura: "",
    Chakra: "",
    PianetaOroscopo: "",
    Significato: "stability, dependability, confidence, intervention",
    SignificatoInverso: "Becoming so conservative you resist all change on principle alone, Ignoring innovations in the name of preserving tradition, Being smug or cocky, Becoming ruthlessly dedicated to profit or pleasure, Being sexually selfish, Bossing others around, especially when you're not empowered to do so",
    BreveDescrizione: "Becoming debt-free, Having more than enough to get by, Making contributions to a savings plan"
  }
];